### ISSUE TITLE
Control styling

### ISSUE THREAD

**Issue by WORMSS** [wheatjs/vueuse-playground#26]
Is it possible to remove all the styling from buttons and select controls please?

```css
button {
  text-transform: none;
  background-color: transparent;
  background-image: none
}
```
Stuff like this is being applied to every button and select and making the UI completely unusable in the preview.

![image](https://github.com/wheatjs/vueuse-playground/assets/1384537/276a21a9-62c7-4fc8-8998-b8fafcdd7027)

```html
<select>
  <option value="test1">Test 1</option>
  <option value="test2">Test 2</option>
  <option value="test3">Test 3</option>
</select>
<input type="button"value="Add">
```
